name: Create Release

on: workflow_dispatch

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Cache Composer Packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            -   name: Install Composer Dependencies
                run: composer install

            - name: Use Node.js 12.x
              uses: actions/setup-node@v3
              with:
                  node-version: 12.x
                  cache: 'npm'
                  cache-dependency-path: "package-lock.json"

            - name: Install NPM Dependencies
              run: npm install

            - name: Create Release Zip
              run: make lint && npm run build && composer run no-dev && npm run create-release-zip

            - name: Create Release Tag
              id: create_release_tag
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ vars.VERSION }}
                release_name: ${{ vars.VERSION }}
                draft: false
                prerelease: false

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release_tag.outputs.upload_url }}
                  asset_path: ./release/${{ github.repository }}.zip
                  asset_name: ${{ github.repository }}-${{ vars.VERSION }}.zip
                  asset_content_type: application/zip
